/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bocor19;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Rayhan
 */
public class EditData extends javax.swing.JFrame {
    
String user="root";
String pswd ="";
String host="localhost";
String db="bocor-19";
String url="";
private Connection Lconnection=null;    

    /**
     * Creates new form EditData
     */
    public EditData() {
        initComponents();
        simpanButton.setEnabled(false);
try {
Class.forName("com.mysql.jdbc.Driver");
url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user
+ "&password="+ pswd;
Lconnection=DriverManager.getConnection(url);
}
catch(ClassNotFoundException e) {
System.out.println("Driver tidak ditemukan");
}
catch (SQLException e){
System.out.println("koneksi gagal:" +
e.toString());
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        alamatTF = new javax.swing.JTextField();
        waktuTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        backGround1 = new yoroshiku.BackGround();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 66, 112, 26));

        jLabel2.setText("Alamat");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 103, 112, 26));

        jLabel3.setText("Waktu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 112, 25));
        getContentPane().add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 66, 160, 26));
        getContentPane().add(alamatTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 106, 160, 23));
        getContentPane().add(waktuTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 140, 160, 25));

        jButton1.setText("Cek ID");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 66, 90, 26));

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });
        getContentPane().add(simpanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 263, 104, 34));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("EDIT DATA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 11, 121, 37));

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 274, -1, -1));

        javax.swing.GroupLayout backGround1Layout = new javax.swing.GroupLayout(backGround1);
        backGround1.setLayout(backGround1Layout);
        backGround1Layout.setHorizontalGroup(
            backGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        backGround1Layout.setVerticalGroup(
            backGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        getContentPane().add(backGround1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
Statement st = Lconnection.createStatement();
ResultSet rs = st.executeQuery
("Select * from pesan_yuk" + " where id='" + idTF.getText() +"'");
if (rs.next()) {
simpanButton.setEnabled(true);
alamatTF.setText(rs.getString("alamat"));
waktuTF.setText(rs.getString("waktu"));
idTF.setText(rs.getString("id"));
} else {
JOptionPane.showMessageDialog(this,"ID: Salah",
"Informasi", JOptionPane.INFORMATION_MESSAGE);
simpanButton.setEnabled(false);
alamatTF.setText("");
waktuTF.setText("");
idTF.setText("");
alamatTF.requestFocus();
}
}
catch (SQLException e){
System.out.println("koneksi gagal " + e.toString());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
        try {
PreparedStatement pStatement =
Lconnection.prepareStatement
("UPDATE pesan_yuk SET alamat=?,waktu=? WHERE id=?");
pStatement.setString(1, alamatTF.getText());
pStatement.setString(2, waktuTF.getText());
pStatement.setString(3, idTF.getText());
if ( pStatement.executeUpdate()>0)
JOptionPane.showMessageDialog(this,"Edit sukses",
"Informasi", JOptionPane.INFORMATION_MESSAGE);
else
JOptionPane.showMessageDialog(this, "Edit gagal",
"Informasi", JOptionPane.INFORMATION_MESSAGE);
pStatement.close();
alamatTF.setText("");
waktuTF.setText("");
idTF.setText("");
}
catch (SQLException e){
System.out.println("koneksi gagal " + e.toString());
}

    }//GEN-LAST:event_simpanButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AdminControlPanel yy;
        yy = new AdminControlPanel();
        yy.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatTF;
    private yoroshiku.BackGround backGround1;
    private javax.swing.JTextField idTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTextField waktuTF;
    // End of variables declaration//GEN-END:variables
}
