/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bocor19;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Rayhan
 */
public class HapusData extends javax.swing.JInternalFrame {
String user="root";
String pswd ="";
String host="localhost";
String db="bocor-19";
String url="";
private Connection Lconnection=null;
private JTable table=null;

    /**
     * Creates new form HapusData
     */
    public HapusData() {
        initComponents();
try {
Class.forName("com.mysql.jdbc.Driver");
url="jdbc:mysql://"+ host +"/"+ db +"?user=" + user
+ "&password="+ pswd;
Lconnection=DriverManager.getConnection(url);
}
catch(ClassNotFoundException e) {
System.out.println("Driver tidak ditemukan");
}
catch (SQLException e){
System.out.println("koneksi gagal:" +
e.toString());
}
tampilTabel();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        backGround1 = new yoroshiku.BackGround();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu1.setText("jMenu1");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 640, 314));

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 368, -1, -1));

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 368, -1, -1));

        javax.swing.GroupLayout backGround1Layout = new javax.swing.GroupLayout(backGround1);
        backGround1.setLayout(backGround1Layout);
        backGround1Layout.setHorizontalGroup(
            backGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        backGround1Layout.setVerticalGroup(
            backGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(backGround1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 400));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
String usrID =
table.getValueAt(table.getSelectedRow(),0).toString();
try {
PreparedStatement pStatement = null;
String sql ="DELETE FROM pesan_yuk WHERE id=?";
pStatement = Lconnection.prepareStatement(sql);
pStatement.setString(1, usrID);
int intTambah= pStatement.executeUpdate();
if (intTambah>0)
JOptionPane.showMessageDialog(this,
"Hapus data sukses", "Informasi",
JOptionPane.INFORMATION_MESSAGE);

else
JOptionPane.showMessageDialog(this,
"Hapus data gagal", "Informasi",
JOptionPane.INFORMATION_MESSAGE);
pStatement.close();
tampilTabel();
}
catch (SQLException e){
System.out.println("koneksi gagal " + e.toString());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AdminControlPanel yy;
        yy = new AdminControlPanel();
        yy.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private yoroshiku.BackGround backGround1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

private Object[][] getData(){
Object[][] data1= null;
try {
Statement st = Lconnection.createStatement();
ResultSet rs = st.executeQuery("Select * from pesan_yuk");
rs.last();
int rowCount= rs.getRow();
rs.beforeFirst();
data1= new Object[rowCount][4];
int no=-1;
while (rs.next()) {
no=no+1;
data1[no][0]=rs.getString("id");
data1[no][1]=rs.getString("alamat");
data1[no][2]=rs.getString("waktu");;
}
st.close();
}
catch (SQLException e){
System.out.println("koneksi gagal " +
e.toString());
}
return data1;
}
private void tampilTabel() {
String[] columnNames = {"id", "alamat", "waktu"};
table = new JTable(getData(), columnNames);
jScrollPane1.setViewportView(table);
}
}